@startuml
object "HP Ship: Ship" as ship1 {
  name = "HP Ship"
  yearBuilt = "2002"
}

object "HP Cruise 212: CruiseShip" as ship2 {
  name = "HP Cruise 212"
  yearBuilt = "2012"
  maxPassengers = 3000
}

object "HP Cargo 118: CargoShip" as ship3 {
  name = "HP Cargo 118"
  yearBuilt = "2023"
  cargoCapacity = 20000
}

@enduml

