@startuml
object "instructor1: Instructor" as instructor1 {
  firstName = "Nima"
  lastName = "Davarpanah"
  officeNumber = "3-2636"
}

object "textbook1: Textbook" as textbook1 {
 title = "Clean Code: A Handbook of Agile Software Craftsmanship"
 author = "Robert Cecil Martin"
 publisher = "Pearson"
}

object "course1: Course" as course1 {
  courseName = "CS5800 - Advanced Software Engineering"
}

course1 o-- instructor1
course1 o-- textbook1
@enduml

