@startuml
object "Titanic:Ship" as ship1 {
  shipName = "Titanic"
  yearBuilt = "March31st,1909"
}

object "MV Gemini:CruiseShip" as ship2 {
  shipName = "MV Gemini"
  yearBuilt = "May30th,1991"
  maxNumberPassengers = 100
}

object "Ever Given:CargoShip" as ship3 {
  shipName = "Ever Given"
  yearBuilt = "September25th,2018"
  cargoCapacityInTonnage = 220940
}

@enduml

